# Generated by Django 4.0.1 on 2022-01-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cartorder_wishlist_useraddressbook_productreview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '10. Reviews'},
        ),
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name_plural': '12. AddressBook'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': '11. Wishlist'},
        ),
    ]
